name: Build and Release

on:
  push:
    branches:
      - electron

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            make_command: make:mac
          - os: ubuntu-latest
            make_command: make:linux
          - os: windows-latest
            make_command: make:win

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g electron-forge
          npm ci

      - name: Make Electron app
        run: npm run ${{ matrix.make_command }}

      - name: Publish Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
