name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Compile for all platforms
      run: bun run compile:all

    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/bridge-executable-win.exe
        asset_name: bridge-executable-win.exe
        asset_content_type: application/octet-stream

    - name: Upload macOS Intel Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/bridge-executable-mac-intel
        asset_name: bridge-executable-mac-intel
        asset_content_type: application/octet-stream

    - name: Upload macOS ARM Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/bridge-executable-mac-arm
        asset_name: bridge-executable-mac-arm
        asset_content_type: application/octet-stream

    - name: Upload Linux x64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/bridge-executable-linux
        asset_name: bridge-executable-linux
        asset_content_type: application/octet-stream

    - name: Upload Linux ARM Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/bridge-executable-linux-arm
        asset_name: bridge-executable-linux-arm
        asset_content_type: application/octet-stream