name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Install electron-packager globally
        run: npm install -g electron-packager

      - name: Build for all platforms
        run: npm run package-all

      - name: Zip Windows Asset
        run: zip -r GPG-Bridge-win.zip GPG-Bridge-win32-x64

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./GPG-Bridge-win.zip
          asset_name: GPG-Bridge-win.zip
          asset_content_type: application/zip

      - name: Zip macOS Asset
        run: zip -r GPG-Bridge-mac.zip GPG-Bridge-darwin-x64 GPG-Bridge-darwin-arm64

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./GPG-Bridge-mac.zip
          asset_name: GPG-Bridge-mac.zip
          asset_content_type: application/zip

      - name: Zip Linux Asset
        run: zip -r GPG-Bridge-linux.zip GPG-Bridge-linux-x64

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./GPG-Bridge-linux.zip
          asset_name: GPG-Bridge-linux.zip
          asset_content_type: application/zip

      - name: Zip Windows Asset
        run: zip -j gpg-bridge-win.zip ./dist/gpg-bridge-win.exe

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./gpg-bridge-win.zip
          asset_name: gpg-bridge-win.zip
          asset_content_type: application/zip

      - name: Zip macOS Intel Asset
        run: zip -j gpg-bridge-mac-intel.zip ./dist/gpg-bridge-mac-intel

      - name: Upload macOS Intel Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./gpg-bridge-mac-intel.zip
          asset_name: gpg-bridge-mac-intel.zip
          asset_content_type: application/zip

      - name: Zip macOS ARM Asset
        run: zip -j gpg-bridge-mac-arm.zip ./dist/gpg-bridge-mac-arm

      - name: Upload macOS ARM Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./gpg-bridge-mac-arm.zip
          asset_name: gpg-bridge-mac-arm.zip
          asset_content_type: application/zip

      - name: Zip Linux x64 Asset
        run: zip -j gpg-bridge-linux-x64.zip ./dist/gpg-bridge-linux-x64

      - name: Upload Linux x64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./gpg-bridge-linux-x64.zip
          asset_name: gpg-bridge-linux-x64.zip
          asset_content_type: application/zip

      - name: Zip Linux ARM Asset
        run: zip -j gpg-bridge-linux-arm.zip ./dist/gpg-bridge-linux-arm

      - name: Upload Linux ARM Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./gpg-bridge-linux-arm.zip
          asset_name: gpg-bridge-linux-arm.zip
          asset_content_type: application/zip
