name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Install electron-packager globally
        run: npm install -g electron-packager

      - name: Build for all platforms
        run: npm run package-all

      - name: Zip Windows Asset
        run: zip -r GPG-Bridge-win.zip GPG-Bridge-win32-x64

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./GPG-Bridge-win.zip
          asset_name: GPG-Bridge-win.zip
          asset_content_type: application/zip

      - name: Zip macOS Asset
        run: zip -r GPG-Bridge-mac.zip GPG-Bridge-darwin-x64 GPG-Bridge-darwin-arm64

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./GPG-Bridge-mac.zip
          asset_name: GPG-Bridge-mac.zip
          asset_content_type: application/zip

      - name: Zip Linux Asset
        run: zip -r GPG-Bridge-linux.zip GPG-Bridge-linux-x64

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./GPG-Bridge-linux.zip
          asset_name: GPG-Bridge-linux.zip
          asset_content_type: application/zip
